### ISSUE TITLE
`parallel_apply` fails for DataFrame > 4M rows

### ISSUE THREAD

**Issue by Arka161** [nalepae/pandarallel#201]
## General

- **Operating System**: Linux (any Ubuntu distro)
- **Python version**: 3.6
- **Pandas version**: 1.1.5
- **Pandarallel version**: 1.6.3

## Acknowledgement

- [X] My issue is **NOT** present when using `pandas` without alone (without `pandarallel`)
- [X] If I am on **Windows**, I read the [Troubleshooting page](https://nalepae.github.io/pandarallel/troubleshooting/)
      before writing a new bug report

## Bug description

`Parallel_apply` seems to have bottlenecks for large DataFrames. If you try `parallel_apply` for a large DataFrames. 

### Observed behavior

I get an error like: 

```
i' format requires -2147483648 <= number <= 2147483647
```
When using the code with `use_memory_f` as `False`. `True` or `None` seems to dump very large Pickle objects which uses my complete storage. The DataFrame has 4M rows and my SSD has 700GB free. I have 512GB of RAM. 

Note: when I downsize the same DF to take around 900k rows, there are no errors or issues.

### Expected behavior:

`parallel_apply` to work correctly. 

## Minimal but working code sample to ease bug fix for `pandarallel` team

Nothing special:

```
df["col"] = df["col"].parallel_apply(func)
```

Where df is a large DF > 4M rows, and `use_memory_f` is `False`.

**Comment by till-m** [comment]
Hi @Arka161,

thanks for reporting this problem. Can you please provide the complete stacktrace instead of the single error line?

I did some quick research and this seems to be a problem occuring with a few libraries that use multiprocessing. See primarily scikit-learn/scikit-learn#3313 and the related [SO Question](https://stackoverflow.com/q/24406937), but also issues mentioning scikit-learn#3313 like microsoft/FLAML#134, ing-bank/probatus#168.

Based on what is mentioned there, I suspect there isn't enough memory (+ there may also be a leak somewhere). Remember that pandarallel trades processing speed for memory usage. As a workaround, you could try splitting your dataframe into smaller sections with fewer rows, applying your functions based on these reduced dataframes, storing the results and loading + concatenating after the fact.

I hope this helps somewhat.

**Comment by till-m** [comment]
I assume this has been resolved. Feel free to reopen if the issue persists.
