### ISSUE TITLE
Document deprecation of shm_size_mb

### ISSUE THREAD

**Issue by mattseymour** [nalepae/pandarallel#79]
I cannot find any documentation on why `pandallel.initialize` :- `shm_size_mb` is deprecated. Neither the docs nor the code explains the reasoning behind it. Could you please comment on why this function argument is now deprecated.

In a future release, it would also be good to implement a deprecation warning on this arg.

**Comment by nalepae** [comment]
`shm_size_mb` is deprecated because in firsts versions, **Pandarallel** used [PyArrow Plasma](https://arrow.apache.org/docs/python/plasma.html). A lot of tickets on **Pandarallel** had as a root cause the usage of **PyArrow Plasma**. So I chose to stop using it.

Because I did not want to break the API, I just chose to deprecate this argument. (You could still use it, but it won't have any impact).

I will add a deprecation warning on the next **Pandarallel** version, thanks for the advice!

**Comment by nalepae** [comment]
Fixed in **Pandarallel v1.4.6**
